### ISSUE TITLE
If a group isn't defined in the group_reference array, those items are never returned after being parsed.

### ISSUE THREAD

**Issue by robertvrabel** [waynestate/parse-promos#6]
In the case below, the parse method does not return the third group (300) at all. It seems like it should, and the key should be the promo_group_id in this case. That way the return could be:

```
$return = [
    ['first-group'] => [],
    ['second-group'] => [],
    [300] => [],
];
```

The Case:

```
<?php
// Simplified stub for reference
$stub['promotions'] = [
    1 => [
        'promo_item_id' => 1,
        'promo_group_id' => 100,
        'group' => [
            'promo_group_id' => 100,
            'title' => 'First Group'
        ],
    ],
    2 => [
        'promo_item_id' => 2,
        'promo_group_id' => 200,
        'group' => [
            'promo_group_id' => 200,
            'title' => 'Second Group',
        ]
    ],
    3 => [
        'promo_item_id' => 3,
        'promo_group_id' => 300,
        'group' => [
            'promo_group_id' => 300,
            'title' => 'Third Group',
        ]
    ],
];

// Define all the groups
$group_reference = [
    100 => 'first-group',
    200 => 'second-group',
];

// Parse the promos
$parsed = $this->parser->parse($stub, $group_reference);
```

**Comment by nickdenardis** [comment]
@robertvrabel I agree, this should return all groups either contained within an ID key or they name per `$group_reference` if one is provided. 

Because of this, that means `$group_reference` should be optional for `parse()` since the results won't rely on a pretty name being present.

**Comment by nickdenardis** [comment]
I don't mind taking this on if you want. 

I also think that after this we can tag a 1.0.0 release? Pretty sure this is close to feature complete and is being used in production, should have probably initially been 1.0 instead of 0.1.
